In [2]:
import tensorflow as tf

常量定义：
**def constant(value, dtype=None, shape=None, name="Const", verify_shape=False)**

In [10]:
a = tf.constant([2,3],name='a')
b = tf.constant([[1,2],[2,3]],name='b')
x = tf.add(a, b, name='x')
sess = tf.Session()
print(sess.run(x))

[[3 5]
 [4 6]]


使用指定值填充：<br>
**tf.zeros(shape, dtype=tf.float32, name=None)**<br>
**tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)**<br>
**tf.ones(shape, dtype=tf.float32, name=None)**<br>
**tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)**<br>

In [12]:
zeros = tf.zeros([2,3], name='zeros',dtype=tf.float32)
sess = tf.Session()
print(sess.run(zeros))
zeros_like = tf.zeros_like(zeros)    
print(sess.run(zeros_like))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


使用指定数据填充：<br>
**tf.fill(dims, value, name=None) **<br>
创建一个dim形状的张量，使用指定值填充。dim是形状张量，value是标量

In [13]:
fill_data = tf.fill([2,3],value=9)
with tf.Session() as sess:
    print(sess.run(fill_data))


[[9 9 9]
 [9 9 9]]


占位符：tf在计算图时可以不需要知道计算时的必须值，而是使用占位符。当需要执行计算时可以稍后提供所需数据。<br>
创建一个占位符：<br>
**tf.placeholder(dtype, shape=None, name=None)**


然后使用字典来填充占位符：

In [ ]:
placeholder_a = tf.placeholder(tf.float32, shape=[3], name='placeholder_a')
constant_a = tf.constant(value=[5,5,5],shape=[3],dtype=tf.float32,name="constant_a")
variable_c = a+b
with tf.Session() as sess:
    print(sess.run(variable_c, {a:[1,2,3]}))